import mysql.connector
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
t=Tk()
t.geometry("500x500")
mydb = mysql.connector.connect(
 host = "localhost",
 user = "root",
 password = "",
 database = "Imanage")
def addbook():
     f2=Frame(bg="sky blue")
     f2.place(x=0,y=0,width=500,height=500)
     HeadFrame=Frame(f2, bd=1, padx=10,pady=5,bg='white',relief=RIDGE)
     HeadFrame.pack(side=TOP)
     ITitle=Label(HeadFrame, font=('arial',35,'bold'), fg='dark blue',text=' Add Books',bg='white')
     ITitle.grid()
     l1= Label(f2,text="ENTER THE BOOK NAME: ",bg="white")
     l1.place(x=80,y=80)
     bname11=Entry(f2,font=("",12),bg="white")
     bname11.place(x=240,y=80,width=150)
     l2= Label(f2,text="ENTER THE BOOK CODE: ",bg="white")
     l2.place(x=80,y=160)
     bcode11=Entry(f2,font=("",12),bg="white")
     bcode11.place(x=240,y=160,width=150)
     l3= Label(f2,text="TOTAL BOOKS: ",bg="white")
     l3.place(x=80,y=240)
     total11=Entry(f2,font=("",12),bg="white")
     total11.place(x=240,y=240,width=150)
     l4= Label(f2,text="ENTER THE SUBJECTS: ",bg="white")
     l4.place(x=80,y=320)
     sub11=Entry(f2,font=("",12),bg="white")
     sub11.place(x=240,y=320,width=150) 
def ttt():
     bname=bname11.get()
     bcode=bcode11.get()
     total=total11.get()
     sub=sub11.get()
     data = [bname,bcode,total,sub]
     sql = "insert into books(bname,bcode,total,subject) values(%s,%s,%s,%s)"
     c = mydb.cursor()
     c.execute(sql,data)
     mydb.commit()
     messagebox.showinfo("message", "add successfully")
     b1=Button(f2,text="submit",bg="white",command=ttt)
     b1.place(x=260,y=400, width=80,height=50)
     b2=Button(f2,text="back",command=home,bg="white")
     b2.place(x=340,y=400, width=80,height=50) 
def issueb():
     f3=Frame(bg='sky blue')
     f3.place(x=0,y=0,width=500,height=500)
     HeadFrame=Frame(f3, bd=1, padx=10,pady=5,bg='white',relief=RIDGE)
     HeadFrame.pack(side=TOP)
     ITitle=Label(HeadFrame, font=('arial',35,'bold'), fg='dark blue',text=' Issue Book ',bg='white')
     ITitle.grid()
     l1= Label(f3,text="ENTER THE NAME: ")
     l1.place(x=80,y=80)
     name1=Entry(f3,font=("",12))
     name1.place(x=240,y=80,width=150)
     l2= Label(f3,text="ENTER THE ROLL NUMBER: ")
     l2.place(x=80,y=160)
     rno1=Entry(f3,font=("",12))
     rno1.place(x=240,y=160,width=150)
     l3= Label(f3,text="ENTER THE BOOK CODE: ")
     l3.place(x=80,y=240)
     code1=Entry(f3,font=("",12))
     code1.place(x=240,y=240,width=150)
     l4= Label(f3,text="ENTER THE DATE: ")
     l4.place(x=80,y=320)
     date1=Entry(f3,font=("",12))
     date1.place(x=240,y=320,width=150)
def fff():
     name=name1.get()
     rno=rno1.get()
     code=code1.get()
     date=date1.get()
     sql = "insert into issue(name,regno,bcode,idate) values(%s,%s,%s,%s)"
     data =[name,rno,code,date]
     c = mydb.cursor()
     c.execute(sql,data)
     mydb.commit()
     messagebox.showinfo("message", "submit successfully")
     b1=Button(f3,text="submit",bg="white",command=fff)
     b1.place(x=260,y=400, width=80,height=50)
     b2=Button(f3,text="back",command=home,bg="white")
     b2.place(x=340,y=400, width=80,height=50)
def submitb():
     f4=Frame(bg='sky blue')
     f4.place(x=0,y=0,width=500,height=500)
     HeadFrame=Frame(f4, bd=1, padx=10,pady=5,bg='white',relief=RIDGE)
     HeadFrame.pack(side=TOP)
     ITitle=Label(HeadFrame, font=('arial',35,'bold'), fg='dark blue',text=' Book submission ',bg='white')
     ITitle.grid()
     l1= Label(f4,text="ENTER THE NAME: ")
     l1.place(x=80,y=80)
     name1=Entry(f4,font=("",12))
     name1.place(x=240,y=80,width=150)
     l2= Label(f4,text="ENTER THE ROLL NUMBER: ")
     l2.place(x=80,y=160)
     regno1=Entry(f4,font=("",12))
     regno1.place(x=240,y=160,width=150)
     l3= Label(f4,text="ENTER THE BOOK CODE: ")
     l3.place(x=80,y=240)
     code1=Entry(f4,font=("",12))
     code1.place(x=240,y=240,width=150)
     l4= Label(f4,text="ENTER THE DATE: ")
     l4.place(x=80,y=320)
     sdate1=Entry(f4,font=("",12))
     sdate1.place(x=240,y=320,width=150)
def ggg():
     name=name1.get()
     regno=regno1.get()
     code=code1.get()
     sdate=sdate1.get()
     sql = "insert into submit(name,regno,bcode,sdate) values(%s,%s,%s,%s)"
     data = [name,regno,code,sdate]
     c = mydb.cursor()
     c.execute(sql,data)
     mydb.commit()
     messagebox.showinfo("message", "submit successfully") 
     b1=Button(f4,text="submit",bg="white",command=ggg)
     b1.place(x=260,y=400, width=80,height=50)
     b2=Button(f4,text="back",command=home,bg="white")
     b2.place(x=340,y=400, width=80,height=50) 
def dbook():
     f5=Frame(bg='sky blue')
     f5.place(x=0,y=0,width=500,height=500)
     HeadFrame=Frame(f5, bd=1, padx=10,pady=5,bg='white',relief=RIDGE)
     HeadFrame.pack(side=TOP)
     ITitle=Label(HeadFrame, font=('arial',35,'bold'), fg='dark blue',text=' RESET ',bg='white')
     ITitle.grid()
     l1= Label(f5,text="ENTER BOOK CODE: ")
     l1.place(x=100,y=250)
     ac1=Entry(f5,font=("",12))
     ac1.place(x=240,y=250,width=150)
     def df():
         ac=ac1.get()
         sql = "delete from books where bcode = %s"
         data = (ac,)
         c = mydb.cursor()
         c.execute(sql,data)
         mydb.commit()
         messagebox.showinfo("message", "delete successfully")
     b1=Button(f5,text="DELETE",bg="white",command=df)
     b1.place(x=260,y=400, width=80,height=50)
     b2=Button(f5,text="back",command=home,bg="white")
     b2.place(x=340,y=400, width=80,height=50) 
def dispbook():
     sql = "select * from books"
     c = mydb.cursor()
     c.execute(sql)
     rows = c.fetchall()
     total=c.rowcount
     f6=Frame()
     f6.place(x=0,y=0,width=500,height=500)
     '''scroll_bar = Scrollbar(t)
     scroll_bar.pack( side = RIGHT,fill = Y)
     mylist = Listbox(t)
     for line in myresult:
     mylist.pack(padx=10,pady=10,fill=BOTH, expand=True)
     scroll_bar.config( command = mylist.yview )''' 
     style.configure("mystyle.Treeview", font=('Calibri', 18),
     rowheight=50) # Modify the font of the body
     style.configure("mystyle.Treeview.Heading", font=('Calibri', 18)) # Modify the font   of the headings
     tv = ttk.Treeview(f6, columns=(1, 2, 3, 4, 5,6), style="mystyle.Treeview")
     tv.heading("1", text="SNO")
     tv.column("1", width=10)
     tv.heading("2", text="Book name")
     tv.column("1", width=5)
     tv.heading("3", text="code")
     tv.column("3", width=5)
     tv.heading("4", text="total")
     tv.column("4", width=5)
     tv.heading("5", text="subject")
     tv.column("6", width=5)
     tv.pack(fill=X)
     for i in rows:
       tv.insert('','end',values=i)
def home():
     f1=Frame(bg="sky blue")
     f1.place(x=0,y=0,width=500,height=500)
     HeadFrame=Frame(f1, bd=1, padx=10,pady=10,bg='white',relief=RIDGE)
     ITitle=Label(HeadFrame, font=('arial',35,'bold'), fg='dark blue',text=' Library Management ',bg='white')
     ITitle.grid()
     #l1= Label(f1,text="LIBARY MANAGEMENT",bg="white")
     #l1.place(x=180,y=40)
     b1=Button(f1,text="ADD BOOK",command=addbook,bg="white")
     b1.place(x=200,y=100,width=80,height=50)
     b2=Button(f1,text="ISSUE BOOK",command=issueb,bg="white")
     b2.place(x=200,y=175,width=80,height=50)
     b3=Button(f1,text="SUBMIT BOOK",command=submitb,bg="white")
     b3.place(x=200,y=250,width=80,height=50)
     b4=Button(f1,text="DELETE BOOK",command=dbook,bg="white")
     b4.place(x=200,y=325,width=80,height=50)
     b5=Button(f1,text="STOCK",command=dispbook,bg="white")
     b5.place(x=200,y=400,width=80,height=50)
home()
t.mainloop()
